apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: warehousewarehouseibft
  namespace: warehouse-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: warehousewarehouseibft
  chart:
    git: https://github.com/nikhilayadav/bevel.git
    ref: sample
    path: platforms/hyperledger-besu/charts/node_orion 
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://5251d33d0fe6fa8880f373731e47e06e3452f8b581481867f9d1a1c37865f52be096e4ace6c5ddbc25bcd9dd066e2ca12bde580d866ef4d80506ce7f44a7da81@validator1.rc.dev2.aws.blockchaincloudpoc-develop.com:15041"
      - "enode://8926955554a74497eddadc347f6693a379233d025b382af141004f52d7fdb5b4fe49c720fd7973dd6ddb74a16b57e25d03e7c4743621434a421fa2639a2dbd8b@validator2.rc.dev2.aws.blockchaincloudpoc-develop.com:15043"
      - "enode://a4e1276a4f42874f3392a75a8bdec35a2d1de141e5ecdf8b990bffd3cd7f6e60fd47fea8dc6cadb179bac26cb45bbe1d2d6aafac776f8e9f578c1402c35dcb0c@validator3.rc.dev2.aws.blockchaincloudpoc-develop.com:15045"
      - "enode://7f0ec7fdc0a5a725da9f48ca507bba2c7689449ab361ddc2a450e46c8c723872a2248b9463e2ff80b7a25596e514234a80275ec20bbb533e76f7d756c5240b4b@validator4.rc.dev2.aws.blockchaincloudpoc-develop.com:15047"
      - "enode://3ddb5efeef3e87ca2c7d1c7c2179f73282dc3a05ef0a085b4486a65d164c881938a75a80a418d2606bf1ad4f072e93610eb32c18c2302d26b87a0f7b6b0d9a4c@carrier.rc.dev2.aws.blockchaincloudpoc-develop.com:15049"
      - "enode://cae847cce9c4240558fd3c907182f1ef719cf4fbf0fc8769661c83cdfe14696d161118dfbaf40094125e2c8fb7aac459153f40f608342c39bde9a7cfe743adf2@manufacturer.rc.dev2.aws.blockchaincloudpoc-develop.com:15052"
      - "enode://60ca7eb7a29206187a738de8e82634d5841e3d72c2499fe276e7988dd0e6d1f3cf66bf509048e293b4fea64fb6cb0cb6daccea365dc113222e464167f8c5d4e1@store.rc.dev2.aws.blockchaincloudpoc-develop.com:15055"
      - "enode://cd1fcc39933b2740fe23601bdb6a1d747a8a4054c3fdf332ea99fc508a89c3ea1f5ebe17fa0bcd93ad0809024a9557c4724c7a76eacfd1de910595c5499c3f4b@warehouse.rc.dev2.aws.blockchaincloudpoc-develop.com:15058"

    metadata:
      namespace: warehouse-bes
      labels:

    liveliness_check:
      enabled: false
 
    proxy:
      provider: ambassador
      external_url: warehouse.rc.dev2.aws.blockchaincloudpoc-develop.com
      p2p: 15058
      rpc: 15059
      tmport: 15060

    images:
      node: hyperledger/besu:21.10.6
      alpineutils: hyperledgerlabs/alpine-utils:1.0
      orion: pegasyseng/orion:1.6.0

    node:
      name: warehouse
      consensus: ibft
      subject: O=Warehouse,OU=Warehouse,L=42.36/-71.06/Boston,C=US
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    orion:
      name: orion
      tls: True
      confdir: /etc/config
      url: "https://warehouse.rc.dev2.aws.blockchaincloudpoc-develop.com"
      nodelist: "\"https://carrier.rc.dev2.aws.blockchaincloudpoc-develop.com:15051\",\"https://manufacturer.rc.dev2.aws.blockchaincloudpoc-develop.com:15054\",\"https://store.rc.dev2.aws.blockchaincloudpoc-develop.com:15057\",\"https://carrier.rc.dev2.aws.blockchaincloudpoc-develop.com\""
      trust: ca-or-tofu
      ports:
        nodeport: 15060
        clientport: 8888

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secretsv2/data/warehouse-bes/crypto/warehouse
      serviceaccountname: vault-auth
      keyname: data
      tmdir: tm
      tlsdir: tls
      role: vault-role
      authpath: besuwarehouse

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NDA1MTQzZGUzMmM4NDc3MDE4NzI4Y2UyMGRiNWJkOTc5YTcxYjAxODQ5NDI0ZjI1MDZhYWU5NTE1YTRhNDI1NzcxMDlhOTQwYWU2YTgzM2Q4MGE5NDgyNDQ5MjM5ZDI5YTZjZGE3Y2ZlYTZkNmIwNDQ1MzZkMzI0N2IwYTY5NGVhOTZlZDdkNTA5YTI5ODI5MzMyYzU2NThhZmYwM2NmNmQxMTMxM2Y4MDg0MDAwMDAwMDBjMCIKfQ==
