apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: carrier-tessera-job
  namespace: carrier-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: carrier-tessera-job
  chart:
    path: platforms/hyperledger-besu/charts/tessera_key_mgmt
    git: https://github.com/nikhilayadav/bevel.git
    ref: test
  values:
    metadata:
      name: carrier-tessera-job
      namespace: carrier-bes
    peer:
      name: carrier        
    image:      
      repository: quorumengineering/tessera:hashicorp-21.7.3
      pullSecret: regcred
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretengine: secretsv2
      authpath: besucarrier
      role: vault-role
      keyprefix: carrier-bes/crypto
      serviceaccountname: vault-auth
      tmprefix: secretsv2/data/carrier-bes/crypto
