apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: wnikivalidator4quorum
  namespace: wniki-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: wnikivalidator4quorum
  helmVersion: v3
  chart:
    git: https://github.com/nikhilayadav/bevel.git
    ref: test
    path: platforms/quorum/charts/node_quorum_validator  
  values:
    replicaCount: 1
    metadata:
      namespace: wniki-quo
      labels:
    images:
      node: quorumengineering/quorum:21.4.2
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      busybox: busybox
      mysql: mysql/mysql-server:5.7
    node:
      name: validator4
      status: default
      consensus: ibft
      subject: O=Validator4,OU=Validator4,L=42.36/-71.06/Boston,C=US
      mountPath: /etc/quorum/qdata
      imagePullSecret: regcred
      keystore: keystore_1
      
      servicetype: ClusterIP
      lock: false
      ports:
        rpc: 8546
        quorum: 21000
        db: 3306
      dbname: demodb
      mysqluser: demouser
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secretsv2/data/wniki-quo/crypto/validator4
      serviceaccountname: vault-auth
      keyname: quorum
      tm_keyname: transaction
      role: vault-role
      authpath: quorumwniki
    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDEwLAogICAgImhvbWVzdGVhZEJsb2NrIjogMCwKICAgICJlaXAxNTBCbG9jayI6IDAsCiAgICAiZWlwMTUwSGFzaCI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgImVpcDE1NUJsb2NrIjogMCwKICAgICJlaXAxNThCbG9jayI6IDAsCiAgICAiYnl6YW50aXVtQmxvY2siOiAwLAogICAgImNvbnN0YW50aW5vcGxlQmxvY2siOiAwLAogICAgInBldGVyc2J1cmdCbG9jayI6IDAsCiAgICAiaXN0YW5idWxCbG9jayI6IDAsCiAgICAiaXN0YW5idWwiOiB7CiAgICAgICJlcG9jaCI6IDMwMDAwLAogICAgICAicG9saWN5IjogMCwKICAgICAgImNlaWwyTmJ5M0Jsb2NrIjogMAogICAgfSwKICAgICJ0eG5TaXplTGltaXQiOiAxMjgsCiAgICAicWlwNzE0QmxvY2siOiAwLAogICAgImlzTVBTIjogZmFsc2UsCiAgICAiaXNRdW9ydW0iOiB0cnVlLAogICAgIm1heENvZGVTaXplQ29uZmlnIjogWwogICAgICB7CiAgICAgICAgImJsb2NrIjogMCwKICAgICAgICAic2l6ZSI6IDEyOAogICAgICB9CiAgICBdCiAgfSwKICAibm9uY2UiOiAiMHgwIiwKICAidGltZXN0YW1wIjogIjB4NjI0YWFmOGQiLAogICJleHRyYURhdGEiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwZjg5YWY4NTQ5NDQ2NjFiZjZlOGU4ZTA0MTczMTQyNmI1MWJiZGI1NWIxY2MwM2VmN2U5NGY3NWFiZTcyZGE5NmRjODM5ZDhlOWQzYjI2NzU2MjJlZWQ2OGRiOWY5NDY5YWUwMmZhODAxMjRhNjE0NTdkY2U2YWU5ODcxZTZiNzYzZjU1Y2Q5NDI1ZTlhYzRjZjVhNTczMDI3MDM1ZGVmN2I1MjJiZDE3NjMyZmVkM2RiODQxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGMwIiwKICAiZ2FzTGltaXQiOiAiMHhlMDAwMDAwMCIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAibWl4SGFzaCI6ICIweDYzNzQ2OTYzNjE2YzIwNjI3OTdhNjE2ZTc0Njk2ZTY1MjA2NjYxNzU2Yzc0MjA3NDZmNmM2NTcyNjE2ZTYzNjUiLAogICJjb2luYmFzZSI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICJhbGxvYyI6IHsKICAgICIyNWU5YWM0Y2Y1YTU3MzAyNzAzNWRlZjdiNTIyYmQxNzYzMmZlZDNkIjogewogICAgICAiYmFsYW5jZSI6ICIweDQ0NmMzYjE1Zjk5MjY2ODdkMmM0MDUzNGZkYjU2NDAwMDAwMDAwMDAwMCIKICAgIH0sCiAgICAiNDY2MWJmNmU4ZThlMDQxNzMxNDI2YjUxYmJkYjU1YjFjYzAzZWY3ZSI6IHsKICAgICAgImJhbGFuY2UiOiAiMHg0NDZjM2IxNWY5OTI2Njg3ZDJjNDA1MzRmZGI1NjQwMDAwMDAwMDAwMDAiCiAgICB9LAogICAgIjY5YWUwMmZhODAxMjRhNjE0NTdkY2U2YWU5ODcxZTZiNzYzZjU1Y2QiOiB7CiAgICAgICJiYWxhbmNlIjogIjB4NDQ2YzNiMTVmOTkyNjY4N2QyYzQwNTM0ZmRiNTY0MDAwMDAwMDAwMDAwIgogICAgfSwKICAgICJmNzVhYmU3MmRhOTZkYzgzOWQ4ZTlkM2IyNjc1NjIyZWVkNjhkYjlmIjogewogICAgICAiYmFsYW5jZSI6ICIweDQ0NmMzYjE1Zjk5MjY2ODdkMmM0MDUzNGZkYjU2NDAwMDAwMDAwMDAwMCIKICAgIH0KICB9LAogICJudW1iZXIiOiAiMHgwIiwKICAiZ2FzVXNlZCI6ICIweDAiLAogICJwYXJlbnRIYXNoIjogIjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIKfQ==
    staticnodes: 
      [
    "enode://3ab0d5069c888c440a7dc2968c240a39f9b10042cae4a5a08db5dae0d8055135ff7ba38e332d27e95a032d94244cc274d275f01df44311df0772162d554709d8@cniki.rc.dev2.aws.blockchaincloudpoc-develop.com:15041?discport=0",
    "enode://da1999c0f9406083bef8e2bb0fdd7cbeed1a0bed2118b78a9bb6f03acd5fdfa784733fffa0461fdf0b881c14fc9973a8fc5f9827ae10002cd17ee5b13044538b@validator1.rc.dev2.aws.blockchaincloudpoc-develop.com:15044?discport=0",
    "enode://8a3d819347dc87525807a0095daed43d6cd1e94d243e7145477954fe1941e4bc295c89da38a0b2ef30c04f57e1c286b2f19e9bd1e3514ed913dcaa3cd498ca5d@mniki.rc.dev2.aws.blockchaincloudpoc-develop.com:15046?discport=0",
    "enode://4a00893789d4e42dacbb45deed4d4b2bb602ed58a6527d1fa7679cfacf5110eb81b55ca767df562f4419ca67d4c2983b981f51757441b602b42f1cced9cba134@validator2.rc.dev2.aws.blockchaincloudpoc-develop.com:15049?discport=0",
    "enode://b4a5e6b33470234bf4db224d79f1fa30c0a26284689f0b248e3fe1f43e082304604ee75bf01ef753b569c36a747777eba4136473124a9af0f4992870a3f11e5d@sniki.rc.dev2.aws.blockchaincloudpoc-develop.com:15051?discport=0",
    "enode://4a6029143db69840d86cf7756caa9b4b965b5d963cb884d55cdfbeca6448e7ea3eda8e9424663b8c6fbe64d53b1ee5977477bfb994ff13bc5e3b81fa4d09d554@validator3.rc.dev2.aws.blockchaincloudpoc-develop.com:15054?discport=0",
    "enode://7ea54afaf968454b612662f4611e8e0e912f4cf77a6967ad1fd243b2dcb4407b5e34d19664dcb96d94a77bc22ab86d60fa9d2171261c255c227d3b31a963dd91@wniki.rc.dev2.aws.blockchaincloudpoc-develop.com:15056?discport=0",
    "enode://f423cacb6ddb9ff41807968c76eead5f80e900f541671d8bdddab4fcee221e3e74441452c0736d92b930ab3abab8d0a8711c67908d9ca4409716244bfa0e2fb3@validator4.rc.dev2.aws.blockchaincloudpoc-develop.com:15059?discport=0"
]
    proxy:
      provider: "ambassador"
      external_url: validator4.rc.dev2.aws.blockchaincloudpoc-develop.com
      rpcport: 15060
      quorumport: 15059
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi
      dbstorage: 1Gi
