##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# This task checks if the geth binary is already in place or not
- name: Check geth
  stat:
    path: "{{ bin_install_dir }}/geth"
  register: geth_stat_result

# This task creates the geth directory
- name: Create geth directory
  stat:
    path: "{{ bin_install_dir }}/geth"
  register: geth_stat_result

# This task downloads the geth tar
- name: Download geth tar 
  get_url:
    url: "https://gethstore.blob.core.windows.net/builds/geth-alltools-linux-amd64-1.10.0-56dec25a.tar.gz"
    dest: "{{ bin_install_dir }}/geth"
    mode: 0777
  when: geth_stat_result.stat.exists == False

# This task creates the bin directory, if it doesn't exist, for storing the geth binary
- name: Create bin directory
  file:
    path: "{{ bin_install_dir }}"
    state: directory
  when: geth_stat_result.stat.exists == False

# This task puts the geth binary to the bin directory created in the above task
- name: Copy geth binary to destination directory
  copy:
    src: "{{ bin_install_dir }}/geth"
    dest: "{{ bin_install_dir }}"
    mode: 0777
    remote_src: yes
  when: geth_stat_result.stat.exists == False
