##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# This task registers a temporary directory
- name: Register temporary directory
  tempfile:
    state: directory
  register: tmp_directory
 
# This task checks if the geth binary is already in place or not
- name: Check geth
  stat:
    path: "{{ bin_install_dir }}/geth"
  register: geth_stat_result

# This task downloads the geth tar
- name: Download geth tar 
  get_url:
    url: "{{ get_url.url }}"
    dest: "{{ tmp_directory.path }}"
    mode: 0440
  when: geth_stat_result.stat.exists == False

# This task creates the bin directory, if it doesn't exist
- name: Create bin directory
  file:
    path: "{{ bin_install_dir }}"
    state: directory
  when: geth_stat_result.stat.exists == False

# This task extracts the tar file containing the geth and bootnode binary
- name: Extracts the tar file containing the geth and bootnode binary
  unarchive:
    src: "{{ tmp_directory.path }}/geth-alltools-linux-amd64-1.10.0-56dec25a.tar.gz"
    dest: "{{ tmp_directory.path }}"
    copy: no  
  when: geth_stat_result.stat.exists == False

# This task puts the geth binary to the bin directory created in the above task 
- name: Copy geth binary to destination directory
  copy:
    src: "{{ tmp_directory.path }}/geth-alltools-linux-amd64-1.10.0-56dec25a/geth"
    dest: "{{ bin_install_dir }}"
    mode: 0755
    remote_src: yes
  when: geth_stat_result.stat.exists == False