apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: notary1db
  annotations:
    fluxcd.io/automated: "false"
  namespace: snikila-ns
spec:
  releaseName: notary1db
  chart:
    path: platforms/r3-corda/charts/h2
    git: https://github.com/nikhilayadav/bevel.git
    ref: test
  values:
    replicaCount: 1
    nodeName: notary1
    metadata:
      namespace: snikila-ns
    image:
      containerName: adopblockchaincloud0502.azurecr.io/h2:2018
      imagePullSecret: regcred
    resources:
      limits: "512Mi"
      requests: "512Mi"
    storage:
      memory: 512Mi
      mountPath: "/opt/h2-data"
      name: awsstorageclass
    service:
      type: NodePort
      p2p:
        port: 10002
      rpc:
        port: 10003
      rpcadmin:
        port: 10005
      tcp:
        port: 9101
        targetPort: 1521
      web:
        targetPort: 81
        port: 8080
      annotations: {}
    deployment:
      annotations: {}
    pvc:
      annotations: {}