apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: storestoreibft
  namespace: store-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: storestoreibft
  chart:
    git: https://github.com/nikhilayadav/bevel.git
    ref: sample
    path: platforms/hyperledger-besu/charts/node_orion 
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://ead5225d9197989ff6770577f0bc6e274af8536300003a144f9f884d8a352dbaeec2d62e650d4330b5af48a83c13aaefae9f118c1c14dfa1417a548e538f2f59@validator1.rc.dev2.aws.blockchaincloudpoc-develop.com:15041"
      - "enode://eeff31614040f44f70dbaed6f21f6ce9d1594fcafa1958d396c9414360558d3db4a2d051230c5ce62761f59e9e480f689b9b5be3e2d1df2e117228e356195407@validator2.rc.dev2.aws.blockchaincloudpoc-develop.com:15043"
      - "enode://59f821c9ac8a2274b4179d9999165c9c10a245643b59869d5c86d352dc088a820abb6fa40712b9edc515b1bf66e75c5bfa4fb8933144ac8db5925053e9934795@validator3.rc.dev2.aws.blockchaincloudpoc-develop.com:15045"
      - "enode://454d1b676b961d8649acb08651adebbe6f9364821691e2f99e09cd520a08a57da1184914b1aa0b83726bacce9468229328e92a20710a8d90cd9043dc4e4871e5@validator4.rc.dev2.aws.blockchaincloudpoc-develop.com:15047"
      - "enode://3d110a0ebfe272affbf46d81a9ce5edbfd44247ac0bded5237d122881df3c44f4001ac48bc8cc9e5fa52c90ee377e264a0188c1ebf6cc5c0c244837af2ff650b@carrier.rc.dev2.aws.blockchaincloudpoc-develop.com:15049"
      - "enode://0cf0c8e53909e237f06818d52974d5fb1b2e713fdb54e77adb695e3e694e4c2191b1eb5e2e21a18b41249aafb59a175337588dda4d5ee405b671b28ffed920e2@manufacturer.rc.dev2.aws.blockchaincloudpoc-develop.com:15052"
      - "enode://812d79a30360cf2b1ed7b7d60ba173f63d8229cc8a06a167c36bc346fb38a70eabbdc4af7502e367f39596e71b617cff3c5c4c1b35b8bbbfad2d01ebf3e18209@store.rc.dev2.aws.blockchaincloudpoc-develop.com:15055"

    metadata:
      namespace: store-bes
      labels:

    liveliness_check:
      enabled: false
 
    proxy:
      provider: ambassador
      external_url: store.rc.dev2.aws.blockchaincloudpoc-develop.com
      p2p: 15055
      rpc: 15056
      tmport: 15057

    images:
      node: hyperledger/besu:21.10.6
      alpineutils: hyperledgerlabs/alpine-utils:1.0
      orion: pegasyseng/orion:1.6.0

    node:
      name: store
      consensus: ibft
      subject: O=Store,OU=Store,L=40.73/-74/New York,C=US
      mountPath: /opt/besu/data
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    orion:
      name: orion
      tls: True
      confdir: /etc/config
      url: "https://store.rc.dev2.aws.blockchaincloudpoc-develop.com"
      nodelist: "\"https://carrier.rc.dev2.aws.blockchaincloudpoc-develop.com:15051\",\"https://manufacturer.rc.dev2.aws.blockchaincloudpoc-develop.com:15054\""
      trust: ca-or-tofu
      ports:
        nodeport: 15057
        clientport: 8888

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secretsv2/data/store-bes/crypto/store
      serviceaccountname: vault-auth
      keyname: data
      tmdir: tm
      tlsdir: tls
      role: vault-role
      authpath: besustore

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NDNmNmZiZmYxNDg4MTY3MmNmOWI5ZmU0MGE0OGY0MTkyM2I0MzdhYjA5NDMwNmM5YzU2OGE2YmU4MTY1Mjc1MjhmMDkxNzllNzhhYmFmZmI0YWQ5NDBhODQ5M2MxOGI3YTQ4ZWJlOGRmYmY2ZjlhNjYyYmYwNTVhZDJmOGU5NGRkYzM2NTk3MzM0YzI1ZTY2NGJiMWE4OWI2MTBjODI1ZDlhOGY2MDg4MDg0MDAwMDAwMDBjMCIKfQ==
