##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# This task checks if the bootnode binary is already in place or not
- name: Check bootnode 
  stat:
    path: "{{ bin_install_dir }}/bootnode"
  register: bootnode_stat_result

# This task creates the bootnode directory
- name: Create bootnode directory
  stat:
    path: "{{ bin_install_dir }}/bootnode"
  register: bootnode_stat_result
  
# This task downloads the bootnode tar 
- name: Download bootnode tar 
  get_url:
    url: "https://gethstore.blob.core.windows.net/builds/geth-alltools-linux-amd64-1.10.0-56dec25a.tar.gz"
    dest: "{{ bin_install_dir }}/bootnode"
    mode: 0777
  when: bootnode_stat_result.stat.exists == False

# This task creates the bin directory, if it doesn't exist
- name: Create bin directory
  file:
    path: "{{ bin_install_dir }}"
    state: directory
  when: bootnode_stat_result.stat.exists == False

# This task puts the bootnode binary to the bin directory created in the above task
- name: Copy bootnode binary to destination directory
  copy:
    src: "{{ bin_install_dir }}/bootnode"
    dest: "{{ bin_install_dir }}"
    mode: 0777
    remote_src: yes
  when: bootnode_stat_result.stat.exists == False
