##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# This task checks if the bootnode binary is already in place or not
- name: Check bootnode 
  stat:
    path: "{{ bin_install_dir }}/bootnode"
  register: bootnode_stat_result

# This task puts the bootnode binary to the bin directory created in the above task
- name: Copy bootnode binary to destination directory
  copy:
    src: "{{ bin_install_dir }}/geth-alltools-linux-amd64-1.10.0-56dec25a/bootnode"
    dest: "{{ bin_install_dir }}"
    mode: 0755
    remote_src: yes
  when: bootnode_stat_result.stat.exists == False
