apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mnikimnikiquorum
  namespace: mniki-quo
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: mnikimnikiquorum
  helmVersion: v3
  chart:
    git: https://github.com/nikhilayadav/bevel.git
    ref: test
    path: platforms/quorum/charts/node_quorum_member
  values:
    replicaCount: 1
    metadata:
      namespace: mniki-quo
      labels:
    images:
      node: quorumengineering/quorum:21.4.2
      alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      tessera: quorumengineering/tessera:21.7.3
      busybox: busybox
      mysql: mysql/mysql-server:5.7
    node:
      name: mniki
      status: default
      consensus: raft
      subject: O=Manufacturer,OU=Manufacturer,L=47.38/8.54/Zurich,C=CH
      mountPath: /etc/quorum/qdata
      imagePullSecret: regcred
      keystore: keystore_1
      
      servicetype: ClusterIP
      lock: false
      ports:
        rpc: 8546
        raft: 50401
        tm: 443
        quorum: 21000
        db: 3306
      dbname: demodb
      mysqluser: demouser
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secretsv2/data/mniki-quo/crypto/mniki
      serviceaccountname: vault-auth
      keyname: quorum
      tm_keyname: transaction
      role: vault-role
      authpath: quorummniki
    tessera:
      dburl: "jdbc:mysql://mniki-tessera:3306/demodb"
      dbusername: demouser
      url: "https://mniki.rc.dev2.aws.blockchaincloudpoc-develop.com:443"
      clienturl: "http://mniki-tessera:8888" #TODO: Enable tls strict for q2t
      othernodes:
        - url: https://cnik.rc.dev2.aws.blockchaincloudpoc-develop.com
        - url: https://mnik.rc.dev2.aws.blockchaincloudpoc-develop.com
        - url: https://snik.rc.dev2.aws.blockchaincloudpoc-develop.com
        - url: https://wnik.rc.dev2.aws.blockchaincloudpoc-develop.com
      tls: "STRICT"
      trust: "TOFU"
    genesis: ewogICAgImFsbG9jIjogewogICAgICAgICIwNzRhMTE1N2U2MTIxOWFmMDAxM2JmMWFiOWZjMzIxNmEwZDhlYWVmIjogewogICAgICAgICAgICAiYmFsYW5jZSI6ICIxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIgogICAgICAgIH0sCiAgICAgICAgIjVjYjlkMWMzNWNmNWI0ZTVkZjUzOTAyYTI5MjdkMzZiMGQ2MzQzOTYiOiB7CiAgICAgICAgICAgICJiYWxhbmNlIjogIjEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiCiAgICAgICAgfSwKICAgICAgICAiOTA0Njg4ZmVlYzNhMTgzMjdiMzgzMmI4MWRiYTRhY2IzZWY5NjI4OSI6IHsKICAgICAgICAgICAgImJhbGFuY2UiOiAiMTAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIKICAgICAgICB9LAogICAgICAgICI5NzZkNTBhZjdmMmYzZThjZjA1ZGZkZTcwNmFlMGZhN2NlZjhmYWNmIjogewogICAgICAgICAgICAiYmFsYW5jZSI6ICIxMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIgogICAgICAgIH0KICAgIH0sCiAgICAiY29pbmJhc2UiOiAiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwIiwKICAgICJjb25maWciOiB7CiAgICAgICAgImJ5emFudGl1bUJsb2NrIjogMCwKICAgICAgICAiY2hhaW5JZCI6IDEwLAogICAgICAgICJjb25zdGFudGlub3BsZUJsb2NrIjogMCwKICAgICAgICAiZWlwMTUwQmxvY2siOiAwLAogICAgICAgICJlaXAxNTBIYXNoIjogIjB4MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMCIsCiAgICAgICAgImVpcDE1NUJsb2NrIjogMCwKICAgICAgICAiZWlwMTU4QmxvY2siOiAwLAogICAgICAgICJob21lc3RlYWRCbG9jayI6IDAsCiAgICAgICAgImlzUXVvcnVtIjogdHJ1ZSwKICAgICAgICAicGV0ZXJzYnVyZ0Jsb2NrIjogMCwKICAgICAgICAicmFmdFNlY29uZHMiOiB0cnVlLAogICAgICAgICJ0eG5TaXplTGltaXQiOiAxMjgKICAgIH0sCiAgICAiZGlmZmljdWx0eSI6ICIweDAiLAogICAgImV4dHJhRGF0YSI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgImdhc0xpbWl0IjogIjB4RTAwMDAwMDAwMCIsCiAgICAibWl4aGFzaCI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwNjQ3NTcyNjE2YzY1Nzg3MzY1NjQ2YzY1NzgiLAogICAgIm5vbmNlIjogIjB4MCIsCiAgICAicGFyZW50SGFzaCI6ICIweDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAiLAogICAgInRpbWVzdGFtcCI6ICIweDAwIgp9
    staticnodes: 
      [
    "enode://19c24dd26c58c7bad6d1a49d3df3d5ff95d3d90b5da9e710e224bbe2817f5234ab01a1e30c7563dbc0654f135f5cd674836e0e452aa9dcbb8cce3d23ad68e273@cniki.rc.dev2.aws.blockchaincloudpoc-develop.com:15041?discport=0&raftport=15043",
    "enode://cde53c6d684eea666cda5820688d444e3ad37bcb6a0007a7f3985e5cbf1410d890feadbe090a0248337a2fc9bf0457c3a6bd4e699254eb6951ebad86c587644d@mniki.rc.dev2.aws.blockchaincloudpoc-develop.com:15044?discport=0&raftport=15046",
    "enode://fa51b8442c4f228cfef5757e07a8ae375fa7f650b1fa67876e77c49fffdd23adce5d668068c5b4c31ae8b49e0592768e13d8f999b958d0db5bf41b5ae6b3e7a8@sniki.rc.dev2.aws.blockchaincloudpoc-develop.com:15047?discport=0&raftport=15049",
    "enode://8ab7c0f4221c46d8dd3f5cc7aa5c72fb1679e00bb28de843d6339428a4133a8963c7781971154b8a28228651b11da2e06cb3ca1215cbfc8509abbb80cfdbcac4@wniki.rc.dev2.aws.blockchaincloudpoc-develop.com:15050?discport=0&raftport=15052"
]
    proxy:
      provider: "ambassador"
      external_url: mniki.rc.dev2.aws.blockchaincloudpoc-develop.com
      portTM: 443
      rpcport: 15045
      quorumport: 15044
  
      portRaft: 15046
    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi
      dbstorage: 1Gi
